# Generated by Django 5.1.7 on 2025-04-22 14:19

import Where2go.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Where2go", "0002_add_user_search_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                default=Where2go.models.default_end_time,
                null=True,
                verbose_name="Время окончания",
            ),
        ),
    ]
