# Generated by Django 5.1.7 on 2025-06-05 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Where2go", "0004_remove_poll_options_poll_voted_categories"),
        (
            "Where2go",
            "0005_customuser_force_password_reset_temporaryaccesslink_and_more",
        ),
    ]

    operations = [] 